---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#
site_name: wiki.h4n.io

repo_url: https://github.com/hbjydev/wiki.h4n.io
repo_name: wiki.h4n.io
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.action.edit
  icon:
    tag:
      monitoring: material/alert-circle
    repo: fontawesome/brands/github
  custom_dir: overrides

copyright: Copyright &copy; 2023 Hayden Young.

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@hayden
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hayden_dev
    - icon: fontawesome/brands/github
      link: https://github.com/hbjydev
  tags:
    Monitoring: monitoring

plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: 'index.md'

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
